config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  namespace :manage do
    resources :restaurants, only: [:show, :new, :index, :edit]
  end

  resources :users do
    resources :restaurants, only: [:create, :update, :destroy, :index, :show]
  end

  resources :restaurants do
    resources :reservations, only: [:new, :create, :update, :edit, :destroy,]
  end

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :party_size, numericality: { only_integer: true }
  validates :party_size, :date_time, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :owner, class_name: 'User'

  # NOTE: This logic is flawed. The controller is too big for the model. The available? method should only expect a datetime and partysize, not the entire reservation object. Need to rewrite controller first, refactor this method and rewrite tests to pass.
  def available?(reservation)
    # current_reso_party_size = reservation.id ? Reservation.find(reservation.id).party_size : 0

    current_capacity = capacity - reservations.sum(:party_size)

    availability = reservation.party_size <= current_capacity # + current_reso_party_size

    reservation.party_size > 0 && availability

  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations
  has_many :businesses, class_name: 'Restaurant', foreign_key: :owner_id


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
  class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations.all
  end


  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.find(params[:id])

    # Assign attributes to reservation but don't save yet
    @reservation.assign_attributes(reservation_params)

    if !@reservation.valid?
      flash[:notice] = "NOT VALID"
      redirect_to @restaurant
    elsif @restaurant.available?(@reservation)
      if @reservation.save
        redirect_to user_path(current_user)
      else
        render :edit
      end
    else
      flash[:notice] = "Sorry, the restauraunt does not currently have enough
                        space for your party of #{@reservation.party_size}.
                        Total capacity is #{@restaurant.capacity}. Please try
                        again later. Remaining capacity is
                        #{(@restaurant.capacity - @restaurant.reservations.sum(:party_size) + Reservation.find(params[:id]).party_size)}"
      render :edit
    end

  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new(
      party_size: reservation_params[:party_size],
      date_time: reservation_params[:date_time],
      user: current_user,
      restaurant: @restaurant
    )
    
    if !@reservation.valid?
      flash[:notice] = "NOT VALID"
      redirect_to @restaurant
    elsif @restaurant.available?(@reservation)

      if @reservation.save
        redirect_to user_path(current_user)
      else
        render 'restaurant/show'
      end

    else
      flash[:notice] = "Sorry, the restauraunt does not currently have enough
                        space for your party of #{@reservation.party_size}.
                        Total capacity is #{@restaurant.capacity}. Please try
                        again later. Remaining capacity is
                        #{(@restaurant.capacity - @restaurant.reservations.sum(:party_size))}"

      redirect_to @restaurant
    end

  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to  user_path(current_user)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:date_time, :party_size)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
    @reservation = Reservation.new
  end

  def update
    @user = current_user
    @business = @user.businesses.find(params[:id])
    if @business.update_attributes(restaurant_params)
      redirect_to manage_restaurants_path, notice: "Restaurant updated!"
    else
      render :show, notice: 'Invalid input.'
    end
  end

  def create
    @user = current_user
    if @user.businesses.create(restaurant_params)
      redirect_to manage_restaurants_path, notice: "Added RestoNamePlaceholder to your managed restaurants!"
    else
      render :new, notice: 'Invalid input.'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to  manage_restaurants_path, notice: "Restaurant DESTROY"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :price, :description, :capacity)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid user name or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to restaurants_path, notice: "Sign-up Successful!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>GortEats</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

  </head>
  <body>
    <!-- edit for foundation -->
    <div class="row">
      <div class="small-12 column">

      <ul> <div class="nav_bar">

      <li> <div class="logo"> <%= link_to "GORTEATS", root_path%> </div> </li>

          <ul>
            <li> <div class="nav_link"> <%= link_to "Manage Restaurants", manage_restaurants_path %> </div> </li>
            <li> <div class="nav_link"> <%= link_to "My Reservations", current_user %> </div> </li>
          </ul>

              <ul>
                <li> <div class="login_signup">
                <% if current_user %>
                  Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
                <% else %>
                  <%= link_to "Log in", new_session_path, class: 'button info small radius' %>  <%= link_to "Sign up", new_user_path, class: 'button info small radius' %>
                <% end %>
                </li>
              </ul>

        </ul> </div>
      </div>
    </div>

      <div class="flash">
        <% if flash[:notice] %>
          <p id="notice"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
          <p id="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>
      </div>
    </div>

  </div>

    <div clas="row">
      <div class="small-12 column">

    <%= yield %>

      </div>
    </div>

  </body>
</html>

app/views/reservations/_form.html.erb
  <h4>New Reservation</h4>

  <%= form_for [@restaurant, @reservation] do |f| %>

  <div class="form">

      <div class="row">
        <div class="small-4">


        <%= f.label :date_time %>
        <%= f.time_field :date_time %>

        <%= f.label :party_size %>
        <%= f.number_field :party_size %>

        <%= f.submit %>
    

    </div>
  </div>

</div>
<% end %>

app/views/reservations/edit.html.erb
<%= form_for [@reservation.restaurant, @reservation] do |f| %>

<div>
  <%= f.label :date_time %>
  <%= f.time_field :date_time %>
</div>

<div>
  <%= f.label :party_size %>
  <%= f.number_field :party_size %>
</div>

<div>
  <%= f.submit %>
</div>

<%= link_to 'Back', user_path(current_user) %>

<% end %>

app/views/restaurants/_form.html.erb
<!-- Manage restaurants form -->

<%= form_for [@user, @restaurant] do |f| %>
  <div class="field">
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </p>
    <p>
      <%= f.label :price %><br>
      <%= f.number_field :price %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |resto| %>
  <li>
    <h3><%= link_to resto.name, resto %></h3>
    <p>
      <strong>Price:</strong>
      <% resto.price.times do %>
        $
      <% end %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= resto.location %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= resto.description %></p>
  </li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<div class="restaurant_info">
  <p>
    <%= @restaurant.name %>
  </p>
  <p>
    <%= @restaurant.location %>
  </p>
  <p>
    <% price = [] %>
    <% @restaurant.price.times do %>
      <% price << '$' %>
    <% end %>
      <%= price.join("") %>
  </p>
    <%= @restaurant.description %>
  <p>
</div>

<div class="reservation form">
  <%= render "reservations/form" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>

<div class="form">

    <div class="row">
      <div class="small-4">

      <%= form.label :name %>
       <%= form.text_field :name %>

      <%= form.label :email %>
      <%= form.email_field :email %>

      <%= form.label :password %>
      <%= form.password_field :password %>

      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
      
      <%= form.submit %>

    </div>
  </div>

</div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p>To create a new reservation, <%= link_to "choose a restaurant", root_path %> from the home page.</p>

<h1>Your Reservations</h1>

<ul>
  <% @user.reservations.each do |reservation| %>

    <li>

        <p> Restaurant:</p>
        <%= reservation.restaurant.name %>


        <p>Location:</p>
        <%= reservation.restaurant.location %>

        <p>Party Size:</p>
        <%= reservation.party_size %>

        <p>Time and Date:</p>
        <%= reservation.date_time %>

    </li>
    <%= link_to "Edit", edit_restaurant_reservation_path(reservation.restaurant, reservation), class: 'button small radius' %>
    <%= link_to "Delete", restaurant_reservation_path(reservation.restaurant, reservation), class: 'button small radius', method: :delete, data: { confirm: "Are you sure you want to delete this?" } %>
  <% end %>
</ul>